---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          resources:
            requests:
              cpu: 333m
              memory: 800Mi
            limits:
              cpu: 333m
              memory: 800Mi
          ports:
            - containerPort: 27017
              protocol: TCP
