---
apiVersion: kustomize.config.k8s.io/v1beta1
bases:
  - ../base/
patchesJson6902:
  - target:
      kind: ConfigMap
      name: ${artifactId}-configmap
      version: v1
    path: configmap-patch.yml
