---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod
      image: ubuntu
      command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 5 ; done"]
      resources:
        requests:
          cpu: 333m
          memory: 800Mi
        limits:
          cpu: 333m
          memory: 800Mi
  restartPolicy: Never