---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /actuator/prometheus
    prometheus.io/port: "443"
    prometheus.io/scheme: https
    prometheus.io/scrape: "true"
  name: ${artifactId}-service
spec:
  selector:
    app: ${artifactId}
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
